events { 
    worker_connections 1024; 
}

http {
    # Định nghĩa Cụm (Cluster) 3 máy chủ backend
    # Tên service phải khớp với tên trong file docker-compose.yml
    upstream gold_ticker_backend {
        server web_backend_1:3000;
        server web_backend_2:3000;
        server web_backend_3:3000;
    }

    server {
        # Nginx lắng nghe cổng 80 (cổng web mặc định)
        listen 80;

        location / {
            # Đẩy yêu cầu vào cụm upstream đã định nghĩa ở trên
            proxy_pass http://gold_ticker_backend;
            
            # Giữ lại thông tin IP thật của người dùng để backend xử lý
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}