events { worker_connections 1024; }
http {
    upstream backend_servers {
        server web_backend_1:3000;
        server web_backend_2:3000;
        server web_backend_3:3000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}