events { 
    worker_connections 1024; 
}

http {
    # Định nghĩa Cụm (Cluster) 3 máy chủ backend
    # Docker DNS tự động phân giải tên service trong cùng network
    upstream gold_ticker_backend {
        # Round Robin là mặc định, không cầndirective nào khác
        server web_backend_1:3000;
        server web_backend_2:3000;
        server web_backend_3:3000;
    }

    server {
        # Nginx lắng nghe cổng 80 public
        listen 80;

        location / {
            # Đẩy yêu cầu vào upstream được định nghĩa ở trên
            proxy_pass http://gold_ticker_backend;
            
            # Giữ lại các Header quan trọng
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}